# Site settings
title: BeeTrip Your Personal Budget Assistant
site.title: BeeTrip Your Personal Budget Assistant
email: hi@beetrip.io
description: > # this means to ignore newlines until "baseurl:"
  Your travel budget & expenses assistant. Track all of your expesnes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://beetrip.github.io" # the base hostname & protocol for your site
twitter_username: beetripio
github_username:  beetrip

# Build settings
markdown: kramdown
